services:
  web:
    build: .
    container_name: technova
    ports:
      - "8080:80"
    restart: always

    volumes:
      - ./website:/usr/share/nginx/html

    networks:
      - technova-network

networks:
  technova-network:
